### ISSUE TITLE
Problem with Macro Factory Add function 

### ISSUE THREAD

**Issue by billbazza** [voipnorm/CE-Deploy#16]
Using the new Macro Factory function and for some reason we are unable to push macros to devices. We can delete, activate and deactivate all fine.

**Comment by voipnorm** [comment]
Issue should be solved in latest releases.

**Comment by billbazza** [comment]
Thanks Chris, I appreciate your effort. 

On 3 Aug 2021, at 20:06, Chris Norman ***@***.***> wrote:

﻿
Issue should be solved in latest releases.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
