### ISSUE TITLE
Macro factory add not working on local deploy

### ISSUE THREAD

**Issue by RamosBruno** [voipnorm/CE-Deploy#28]
Hi,

I'm opening this issue because i'm having the same trouble in local mode.

When i try to add a macro to a device the ssh connection don't work because all the special chars are not escaped, the ssh connection fails and the WS connection works but don't upload the macro.

When I remove all special chars the macro is uploaded, in my case i need to remove :

      '    /*var regex = /^sd_([a-zA-Z0-9@_\\-\\.]+)$/;*/\n' +
      '      var regex = /([a-zA-Z0-9@_\\-\\.]+)$/;\n' +

      `            helpPopUp("Besoin d'aide ?", "Grâce à ce bouton vous pourrez rejoindre une conférence. Pensez à vous munir de l'identifiant de la conférence");\n` +

Those lines come from the renderer.log

Electron version: 16.2.3
CE-Deploy version: 10.4.0

**Comment by voipnorm** [comment]
What error do you get from CE-Deploy?

**Comment by RamosBruno** [comment]
I've got that kind of errors when the upload fails

[2022-06-20 11:06:05.576] [error] (macroEndpoint)        Connection terminated remotely
[2022-06-20 11:06:05.577] [error] (macroEndpoint)        SSH failed to connect trying to use Websockets

when i try with a shorter file without special chars it works, but not with longer files and/or special chars

**Comment by voipnorm** [comment]
Can you send me the macro with special characters in a 1:1 space in Webex. Will take  a closer look.

**Comment by voipnorm** [comment]
No response.
